[package]
name = "vault"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10"          # AES-GCM encryption
rand = "0.8"              # random number generation
argon2 = "0.4"            # password-based key derivation
bincode = "1.3"           # binary serialization
serde = { version = "1.0", features = ["derive"] }
rpassword = "7.0"         # for password prompt without echo
sha2 = "0.10"             # for hashing keys (file key derivation)
clap = { version = "4", features = ["derive"] }  # CLI arg parsing
chrono = "0.4"            # timestamping logs
anyhow = "1.0.98"
